### ISSUE TITLE
Inplace ReLU's are unnecessary and wrong

### ISSUE THREAD

**Issue by artyompal** [osmr/imgclsmob#13]
Hi guys

I'd like to thank you for this wonderful collection! One little issue I found is, there's a lot of code like this:
```
self.activ = nn.ReLU(inplace=True)
...
x = self.activ(x)
```
which modifies both old copy of x and a new copy (https://discuss.pytorch.org/t/one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation/12578/7). This results in the following error when I try to use Xception (I'm using PyTorch 1.0.0):
```
Traceback (most recent call last):
  File "./train_j13_xception.py", line 497, in <module>
    train(train_loader, model, criterion, optimizer, epoch, lr_scheduler)
  File "./train_j13_xception.py", line 282, in train
    loss.backward()
  File "/home/cppg/.local/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/cppg/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
Command exited with non-zero status 1
```
Removing of `inplace=True` fixes this. It's an easy search-and-replace fix, but I saw this in many files, so I didn't want to push a giant PR.

Cheers

**Comment by osmr** [comment]
Hi @artyompal ,
Thanks for the bug report. Starting with 0.0.40 version of `pytorchcv` `Xception` and `PolyNet` models should be trained without errors.
