### ISSUE TITLE
where is the .common module?

### ISSUE THREAD

**Issue by mohhao** [osmr/imgclsmob#17]

**Comment by osmr** [comment]
`Common` modules for each frameworks are:
- `/gluon/gluoncv2/models/common.py`
- `/pytorch/pytorchcv/models/common.py`
- `/chainer_/chainercv2/models/common.py`
- `/keras_/kerascv/models/common.py`
- `/tensorflow_/tensorflowcv/models/common.py`

**Comment by mohhao** [comment]
> `Common` modules for each frameworks are:
> 
> * `/gluon/gluoncv2/models/common.py`
> * `/pytorch/pytorchcv/models/common.py`
> * `/chainer_/chainercv2/models/common.py`
> * `/keras_/kerascv/models/common.py`
> * `/tensorflow_/tensorflowcv/models/common.py`

thank you
