### ISSUE TITLE
shufflenet v2 pretrained models

### ISSUE THREAD

**Issue by ArsenLuca** [osmr/imgclsmob#2]
THIS IS such a COOL project!
Would you please share the imagenet-pretrained shufflenet v2 x1.0 model?Thanks very much @osmr

**Comment by osmr** [comment]
I'm working on it. But the pretrained model will be ready not earlier than in 2 weeks.

**Comment by ArsenLuca** [comment]
Looking forwards to more great models

**Comment by osmr** [comment]
Pay attention to the "ShuffleNetV2c x1.0" model. This pretrained model demonstrates relatively good quality.
