### ISSUE TITLE
SqueezeNext missing 

### ISSUE THREAD

**Issue by kaustubh-pandey** [osmr/imgclsmob#22]
In pytorch/pytorchcv/model_provider.py , under _models on line 108 , squeezenext is missing although it has been imported in line 47

**Comment by osmr** [comment]
SqueezeNext model names are the following:
- sqnxt23_w1, 
- sqnxt23_w3d2,
- sqnxt23_w2,
- sqnxt23v5_w1,
- sqnxt23v5_w3d2,
- sqnxt23v5_w2.
