### ISSUE TITLE
download address for pth.zip

### ISSUE THREAD

**Issue by yangninghua** [osmr/imgclsmob#25]
Hello, is there any download address for pth.zip, one download is too slow?

**Comment by osmr** [comment]
Hi. All weights for models are in separate archives on GitHub. There is no single archive with all models at once. 

Sometimes GitHub works very slowly and downloading a specific model can be very long.  Often in this case it is easier to interrupt the download, and try again, or see where the download is from (this information is printed to the console) and download the archive manually by `wget`.

Note that model weights are downloaded only once upon first use. All model weights are cached. For example, PyTroch models are cached in `~/.torch/models` folder. See the download logic in the `pytorch/pytorchcv/models/model_store.py` module.
