### ISSUE TITLE
Pretrained weights for efficentnet b4 & b5

### ISSUE THREAD

**Issue by johnlundberg** [osmr/imgclsmob#26]
Hi, I noticed that weights for EfficientNet B4 and B5 have been released now, https://github.com/tensorflow/tpu/issues/404#issuecomment-502529084

Do you have plans on converting those weights and making available for your keras implementation of EfficientNet B4 and B5?

In any case, thanks for this amazing resource

**Comment by osmr** [comment]
Hi, thanks for the information. I will do it.
