### ISSUE TITLE
pretrained models not found, example: seresnet101b

### ISSUE THREAD

**Issue by reserena** [osmr/imgclsmob#28]
I could not get some of the models that are included your keys. An example would be seresnet101b.
I used ptcv_get_model('seresnet101b', pretrained=True)
 
I did some digging and the model seem to be missing in the _model_sha1... as there are 691 models returned from pytorchcv.model_provider._models.keys() but only 444 models exist in _model_sha1 in model_store.py. 

could you please add the missing models or fix the keys?

Thanks.

**Comment by osmr** [comment]
Hi. You are right, the list of pre-trained models is in the `model_store.py` script. In turn, the `model_provider.py` script contains a list of supported models (see the comment on the `get_model` method). The list of "supported" models is actually a list of more or less well-known presets for implemented model families. Some of these "supported" models are in the learning process, sometimes for months. Obviously, they cannot be present in the list of already trained models.
