### ISSUE TITLE
naming of models is inconsistent with HTML table

### ISSUE THREAD

**Issue by charlesmartin14** [osmr/imgclsmob#30]
I am finding that the names of the models are difficult to match to the reported rows in the HTML table

For example, on the HTML tables we have

`ResNet-18 x0.25 | 39.62 | 17.85 | 3,937,400 | 270.94M | Converted from GL model (log)
`

But in the python code we have

`resnet18_wd4`

Do you have a lookup table or some set of regular expressions that would allow us to match the model names to the HTML tables ?

We have been able to match 370 of the 444 models but still a lot of work to do

**Comment by osmr** [comment]
Hi Charles,

If you use some kind of script for table parsing, than I would recommend to parse the last column of the table. It contains links to log-files. The name of log-file exactly matches to name of the corresponding weight file. The first part of the file stem (before `-` symbol) is exactly the model name.

For your example the link to log file is `https://github.com/osmr/imgclsmob/releases/download/v0.0.262/resnet18_wd4-1785-fe79b31f.pth.log`. The first part of the file stem is `resnet18_wd4`.

If you parse the tables manually, you can hover over the `(log)` and see a link to the log-file in the browser.
