### ISSUE TITLE
Using classifiers as feature extractors

### ISSUE THREAD

**Issue by doraemon96** [osmr/imgclsmob#37]
Hi, this might be an off-topic question.

I was wondering if you'd be able to help me.
I'm trying to import resnet-10 as a feature extractor to TensorFlow's Object Detection API.
I posted a question at [stackoverflow](https://stackoverflow.com/questions/58084579/import-feature-extractor-into-tensorflow-object-detection-api), and I wanted to know if my way of importing only the top-most layers (those that don't convert the model into a classifier) was right.

Any other help solving the issue is welcome!
Thanks

**Comment by osmr** [comment]
Hi. Better if someone helps you. Please note that in your code at stackoverflow there is neither graph creation nor initialization by loaded weights.

**Comment by doraemon96** [comment]
You are completely right. I overlooked that the function get_resnet() only calculates the parameters to feed to ResNet(). I'll fix that, sorry, I was in a hurry to get it working and I got increasingly frustrated, I'll take a look at it tomorrow.

Thanks a lot for the help anyways. I'll keep you posted if I figure out how to get it working.

**Comment by qixuxiang** [comment]
@doraemon96 you may use new tf2.0 new api to solve the problem, I am also trying to use backbone a feature extractor, looking forward to your final solution!

**Comment by osmr** [comment]
You can use the `tf2cv` package for experiments with TensorFlow 2.0.
