### ISSUE TITLE
Squeezenext sqnxt23v5_w2 callbacks error

### ISSUE THREAD

**Issue by wanx4910** [osmr/imgclsmob#38]
checkpoint = ModelCheckpoint('./gdrive/My Drive/MLAI_files/project-images/Full_Dataset/squeezenext_weights.{epoch:02d}-{val_loss:.2f}.hdf5',
                             monitor='val_loss', save_best_only=True, mode='min')
callbacks_list = [checkpoint]
hist = new_model.fit_generator(generator = my_gen(train_generator),
                              steps_per_epoch = STEP_SIZE_TRAIN,
                              validation_data = my_gen(valid_generator),
                              validation_steps = STEP_SIZE_VALID,
                              epochs = 3,
                              callbacks = callbacks_list)

Epoch 1/3
 38/377 [==>...........................] - ETA: 3:54 - loss: 2.0859 - acc: 0.2188/usr/local/lib/python3.6/dist-packages/PIL/Image.py:914: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images
  'to RGBA images')
117/377 [========>.....................] - ETA: 2:35 - loss: 2.0482 - acc: 0.2356/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:742: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
377/377 [==============================] - 221s 586ms/step - loss: 2.0704 - acc: 0.2301 - val_loss: 5.2917 - val_acc: 0.2820
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-136-f588a935fd5c> in <module>()
      4                               validation_steps = STEP_SIZE_VALID,
      5                               epochs = 3,
----> 6                               callbacks = callbacks_list)

12 frames
/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in get_json_type(obj)
     89             return obj.__name__
     90 
---> 91         raise TypeError('Not JSON Serializable: %s' % (obj,))
     92 
     93     from .. import __version__ as keras_version

TypeError: Not JSON Serializable: <module 'tensorflow' from '/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py'>

**Comment by osmr** [comment]
Hi. Does it work with other models?

**Comment by wanx4910** [comment]
You mean other models in the kerascv package? No
But I have try the keras_squeezenet model in parallel and it works there.

checkpoint = ModelCheckpoint('./gdrive/My Drive/MLAI_files/project-images/Full_Dataset/weights.{epoch:02d}-{val_loss:.2f}.hdf5',
                             monitor='val_loss', save_best_only=True, mode='min')
callbacks_list = [checkpoint]
for layer in base_model.layers:
    layer.trainable = False
    
model.compile(optimizer = 'adam',
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])
hist = model.fit_generator(generator = my_gen(train_generator),
                           steps_per_epoch = STEP_SIZE_TRAIN,
                           validation_data = my_gen(valid_generator),
                           validation_steps = STEP_SIZE_VALID,
                           callbacks = callbacks_list,
                           epochs = 3)

Epoch 1/3
252/377 [===================>..........] - ETA: 1:05 - loss: 1.0875 - acc: 0.5360/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:742: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
377/377 [==============================] - 208s 552ms/step - loss: 1.0899 - acc: 0.5334 - val_loss: 1.2154 - val_acc: 0.4525
Epoch 2/3
160/377 [===========>..................] - ETA: 1:46 - loss: 1.0590 - acc: 0.5508/usr/local/lib/python3.6/dist-packages/PIL/Image.py:914: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images
  'to RGBA images')
377/377 [==============================] - 193s 511ms/step - loss: 1.0621 - acc: 0.5491 - val_loss: 1.2249 - val_acc: 0.4262
Epoch 3/3
377/377 [==============================] - 197s 524ms/step - loss: 1.0689 - acc: 0.5425 - val_loss: 1.4601 - val_acc: 0.3115
Exception ignored in: <generator object my_gen at 0x7f20da81b5c8>
RuntimeError: generator ignored GeneratorExit
Exception ignored in: <generator object my_gen at 0x7f20da81ba40>
RuntimeError: generator ignored GeneratorExit

**Comment by wanx4910** [comment]
a = base_model.layers[422].output
from keras.models import Sequential
model_1 = Sequential()
output = Dense(4, activation='softmax')(a)
new_model = Model(base_model.input, output)

I only removed the last layer and put my own FC layer on to do my own classification. Have you been able to replicate my error?

**Comment by osmr** [comment]
Sorry, I cannot reproduce your error. Because I don’t know either your Keras configuration (version, backend, keras.json, additional pip packages), or the script that you run. Perhaps none of my models will suit your configuration/script, with or without modification. If you localize the problem, I will gladly update the models for Keras.

**Comment by wanx4910** [comment]
I want to post my ipynb but I don't seem to be able to upload it.

**Comment by osmr** [comment]
I would recommend putting it in your repo and providing a link. Maybe someone else besides me will look and find a possible error.

**Comment by wanx4910** [comment]
https://github.com/wanx4910/squeezenext-notebook
Here is the notebook and I ran a pip list which shows all the dependencies on the colab instances.
Cheers.

**Comment by osmr** [comment]
I do not see the problems that you are describing. Update all relevant packages (keras, tensorflow, kerascv).
