### ISSUE TITLE
Does the tensorflow model support TFRecords data?

### ISSUE THREAD

**Issue by shenlinyao** [osmr/imgclsmob#39]
in this example:
`net = tfcv_get_model("resnet18", pretrained=True, data_format="channels_first")
x = tf.placeholder(dtype=tf.float32, shape=(None, 3, 224, 224), name="xx")
y_net = net(x)
with tf.Session() as sess:
    tfcv_init_variables_from_state_dict(sess=sess, state_dict=net.state_dict)
    x_value = np.zeros((1, 3, 224, 224), np.float32)
    y = sess.run(y_net, feed_dict={x: x_value})`
I replace the x with TFRecord by tf.parse_single_example. But it seems stuck?

**Comment by osmr** [comment]
TFRecord is not supported.
