### ISSUE TITLE
ValueError: Dimension 2 in both shapes must be equal, but are 3 and 64. Shapes are [7,7,3,64] and [7,7,64,3]. for 'Assign' (op: 'Assign') with input shapes: [7,7,3,64], [7,7,64,3].

### ISSUE THREAD

**Issue by flower96** [osmr/imgclsmob#42]
Hello! I download the resnet-18 model weights(resnet18-0952-0817d058.h5) but it doesn't contain the model structure. So I download the common.py and the resnet.py. The code is shown as follows:
my enviornment: python 3.6, tensorflow version: 1.10.0, keras: 2.2.5

`from keras.models import load_model
path = "C://Users//ME//.keras//models//resnet18-0952-0817d058.h5"

model = resnet18()
model.load_weights(path)
x = np.ones((1,224, 224,3), np.float32)
y = model.predict(x)`

The problem occurs as the "ValueError: Dimension 2 in both shapes must be equal, but are 3 and 64. Shapes are [7,7,3,64] and [7,7,64,3]. for 'Assign' (op: 'Assign') with input shapes: [7,7,3,64], [7,7,64,3]."

**Comment by osmr** [comment]
Hi, When loading pretrained models, use the function `load_model` from `kerascv.models.model_store`:
```
from kerascv.models.model_store import load_model
load_model(model, path)
```

**Comment by flower96** [comment]
Hello! I did it in this way(maybe I misunderstand your idea), as the code shows:

`from kerascv.models.model_store import load_model
import numpy as np

path = "/notebooks/code/resnet18-0952-0817d058.h5"

model = resnet18()
model = load_model(model, path)
x = np.zeros((1, 224, 224, 3), np.float32)
y = model.predict(x)` 
then the problem occurs as
AttributeError                            Traceback (most recent call last)
<ipython-input-4-877de0306472> in <module>
      7 model = load_model(model, path)
      8 x = np.zeros((1, 224, 224, 3), np.float32)
----> 9 y = model.predict(x)
     10 print(y)

AttributeError: 'NoneType' object has no attribute 'predict'
And do I need to define the model structure(model = resnet18())?

**Comment by flower96** [comment]
I fixed the bug, thank you so much!

**Comment by osmr** [comment]
You are welcome
