### ISSUE TITLE
problem in using your valuable codes.

### ISSUE THREAD

**Issue by aif2017** [osmr/imgclsmob#44]
thank you for your nice work. i want to use your classifiers for my thesis. but I need convolutional outputs. but as I try there isn't any way to get this layers output in tf2cv because you have used sequential model. do you know another way to use it?

**Comment by osmr** [comment]
Hi @aif2017, do you mean the following?:
```
from tf2cv.model_provider import get_model as tf2cv_get_model
import tensorflow as tf

net = tf2cv_get_model("resnet18", pretrained=True, data_format="channels_last")
x = tf.random.normal((1, 224, 224, 3))
y_net = net(x)
print(y_net.shape)

net2 = tf2cv_get_model("resnet18", pretrained=True, data_format="channels_last").features
y_net2 = net2(x)
print(y_net2.shape)

net3 = tf2cv_get_model("resnet18", pretrained=True, data_format="channels_last").features
net3._layers.pop()
y_net3 = net3(x)
print(y_net3.shape)
```

**Comment by aif2017** [comment]
thx for your help. wish you all the best!

**Comment by aif2017** [comment]
> 
> 
> thx for your help. wish you all the best!

Unfortunately my main problem remain unsolved!
at the end I need a model from your classifier with three outputs from different stages.(eg (20,20,256),(40,40,256),(80,80,512) )
