### ISSUE TITLE
Allow tf2 models to be saved

### ISSUE THREAD

**Issue by shachargluska** [osmr/imgclsmob#46]
Currently models obtained by calling tf2cv.model_provider can't be saved by tensorflow.
This makes it difficult to use in another context - feature extractor, served by an application, converted via tflite, etc..

For example:
`net = tfcv_get_model(model_name, pretrained=True, data_format="channels_last")
net.save(file_path)`
results in:
`NotImplementedError: Saving the model to HDF5 format requires the model to be a Functional model or a Sequential model. It does not work for subclassed models, because such models are defined via the body of a Python method, which isn't safely serializable. Consider saving to the Tensorflow SavedModel format (by setting save_format="tf") or using 'save_weights'.`

I figured I can bypass this restriction by directly accessing the underlying keras model:
`net.features.save(file_path)`
But this results in
`NotImplementedError: Layers with arguments in '__init__' must override 'get_config'`

Will it be possible to support this?

**Comment by osmr** [comment]
I do not plan to implement saving the model graph to a file in the near future. Use the method `save_weights` to save the model weights to a file.

**Comment by shachargluska** [comment]
I see, thanks!
I managed to get the weights, but not sure how to get the model architecture.
The issue here is more about the model configuration, which can be loaded by Keras model.load.

**Comment by helgisol** [comment]
Model architecture is in your model script. Until you deploy or port the model, you don't need the model graph in the file.

**Comment by osmr** [comment]
In most research tasks, this is redundant functionality, since your architecture is always available as a model script. You can change the script on the fly and load the same weights. Sometimes it helps a lot.  Implementing the `get_config` method in all layers will take a lot of time.
