### ISSUE TITLE
Support for Edge TPU optimized classifiers

### ISSUE THREAD

**Issue by shachargluska** [osmr/imgclsmob#48]
This is an awesome collection of classifiers, with many classifiers having multiple variations for speed/accuracy tradeoff.
Several state of the art classifiers are included such as mobilenet_v3 and efficient-net.
These networks also have Edge-Tpu specific variations:
EfficientNet-EdgeTPU (small, medium & large): https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet/edgetpu
https://ai.googleblog.com/2019/08/efficientnet-edgetpu-creating.html

Mobilenet_v3 edgetpu:
https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet#mobilenet-edgetpu-latency
https://ai.googleblog.com/2019/11/introducing-next-generation-on-device.html

Will it be possible to add them?

**Comment by osmr** [comment]
Yes, it is possible.
