### ISSUE TITLE
mobilenet-v2 architecture

### ISSUE THREAD

**Issue by jakc4103** [osmr/imgclsmob#49]
Hi
I've check the [original paper](https://arxiv.org/abs/1801.04381) and this two repos ([caffe](https://github.com/shicai/MobileNet-Caffe), [pytorch](https://github.com/tonylins/pytorch-mobilenet-v2)) of mobilenet-v2.  
I found that the mobilenet-v2 implementation in [pytorchcv](https://pypi.org/project/pytorchcv/) seems to have an additional conv-bn-relu block at the top of model comparing to normal mobilenet-v2.  
Was that intended to be?

**Comment by osmr** [comment]
Do you mean a classifier (`output`) implemented not as a fully connected module but as a convolutional one?

**Comment by jakc4103** [comment]
My mistake. I double checked it. Turns out it was this [repo](https://github.com/tonylins/pytorch-mobilenet-v2) that missing a conv-bn-relu block
