### ISSUE TITLE
raise MXNetError(py_str(_LIB.MXGetLastError()))

### ISSUE THREAD

**Issue by jttqbc666** [osmr/imgclsmob#58]
Traceback (most recent call last):

  File "<ipython-input-1-4cce3cf1d696>", line 1, in <module>
    runfile('D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/train_ke.py', args='--num-gpus=1 --model=resnet18 --save-dir=../imgclsmob_data/resnet18_a/ --batch-size=2  -j=12 --num-epochs=200 --lr=0.5 --attempt=1 --start-epoch=1', wdir='D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master')

  File "D:\ruanjian\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\ruanjian\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/train_ke.py", line 322, in <module>
    main()

  File "D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/train_ke.py", line 294, in main
    resize_inv_factor=args.resize_inv_factor)

  File "D:\Artificial_Intelligence\anaconda_spyder\imgclsmob-master\keras_\utils.py", line 66, in get_data_rec
    pca_noise=lighting_param,

  File "D:\ruanjian\anaconda\lib\site-packages\mxnet\io\io.py", line 960, in creator
    ctypes.byref(iter_handle)))

  File "D:\ruanjian\anaconda\lib\site-packages\mxnet\base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

MXNetError: [11:02:41] C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\dmlc-core\src\io\local_filesys.cc:127: LocalFileSystem.ListDirectory ../imgclsmob_data/imagenet_rec error: No such process

Script command line:
D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/train_ke.py --num-gpus=1 --model=resnet18 --save-dir=../imgclsmob_data/resnet18_a/ --batch-size=2 -j=12 --num-epochs=200 --lr=0.5 --attempt=1 --start-epoch=1
Script arguments:
Namespace(attempt=1, batch_size=2, dtype='float32', input_size=224, log_interval=50, log_packages='keras', log_pip_packages='keras, keras-mxnet, keras-applications, keras-preprocessing', logging_file_name='train.log', lr=0.5, model='resnet18', momentum=0.9, num_epochs=200, num_gpus=1, num_workers=12, optimizer_name='nag', rec_train='../imgclsmob_data/imagenet_rec/train.rec', rec_train_idx='../imgclsmob_data/imagenet_rec/train.idx', rec_val='../imgclsmob_data/imagenet_rec/val.rec', rec_val_idx='../imgclsmob_data/imagenet_rec/val.idx', resize_inv_factor=0.875, resume='', resume_state='', save_dir='../imgclsmob_data/resnet18_a/', save_interval=4, seed=8214, start_epoch=1, use_pretrained=False, wd=0.0001)
Env_stats:
{
    "keras": null,
    "keras-mxnet": null,
    "keras-applications": null,
    "keras-preprocessing": null,
    "python": "3.7.3",
    "pwd": "D:\\Artificial_Intelligence\\anaconda_spyder\\imgclsmob-master\\common",
    "git": "unknown",
    "platform": "Windows-10-10.0.18362-SP0"
}
From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

From D:\ruanjian\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

**Comment by osmr** [comment]
The training script for Keras implies that the backend of Keras is MXNet.
