### ISSUE TITLE
How to use it for pose estimation

### ISSUE THREAD

**Issue by hundanLi** [osmr/imgclsmob#59]
How to use it for pose estimation, please? Thank you for your reply.

**Comment by osmr** [comment]
I would recommend to explore https://gluon-cv.mxnet.io/tutorials/index.html to start.

**Comment by hundanLi** [comment]
Yes, I have try it out. It's wonderful. What about implementation version in pytorch?

**Comment by osmr** [comment]
In fact, what is in the repository now for the human pose estimation is primarily the machanical transfer of the gluon-cv code on pytorch.

**Comment by hundanLi** [comment]
Thank you for your reply.
