### ISSUE TITLE
Are there recommended input shape for each model?

### ISSUE THREAD

**Issue by tucan9389** [osmr/imgclsmob#66]
Hi, I'm an iOS app developer who is interesting in ML. 
Firstly, thank you for sharing your awesome vision modeling project.

I want to support `imgclsmob`'s pre-trained models on my repositories which provide baseline code for inferencing various ML models on iOS devices. 

I converted all `imgclsmob`'s pre-trained pose estimation model to tflite with `(1,224,224,3)` input shape. But I think each model has an optimized input shape that was used on training.

Are there recommended input shape for each model? 

Here is the issue what I'm working:
https://github.com/tucan9389/PoseEstimation-TFLiteSwift/issues/59

Thank you.

**Comment by osmr** [comment]
Nice work!
To answer your question, see the source code of each model, in particular, the default value of the `in_size` argument. In most cases it's `(1, 256, 192, 3)`.

**Comment by tucan9389** [comment]
- 256: height
- 192: width

Right?

Now I’m testing all pose models provided by this repo. When I’m done, I’ll share it.

Thank you!
