### ISSUE TITLE
Cannot save model

### ISSUE THREAD

**Issue by dinhkhanh-ho** [osmr/imgclsmob#71]
Hi,
I tried to get a pretrained model from kerascv and to simply save this model as following codes:

`from kerascv.model_provider import get_model

net = get_model("resnet18", pretrained=True)
net.save(os.getcwd() + "/model/test.h5")`

However, an error has been occurred like that: 
TypeError: Not JSON Serializable: <module 'tensorflow' from '/home/username/anaconda3/envs/env_name/lib/python3.7/site-packages/tensorflow/__init__.py'>

I understood that save_weights method can help, but I need a single model file .h5 including model architecture and weights for quantizing the model with tflite.

Any help, please? Thanks!

**Comment by dinhkhanh-ho** [comment]
I understood that save_weights method can help, but I need a single model file .h5 including model architecture and weights for quantizing the model with tflite.

**Comment by osmr** [comment]
Sorry, I was not engaged in such a task. Maybe someone else will help.
