### ISSUE TITLE
How to visualize the network and use it in tensorflow 2.0?

### ISSUE THREAD

**Issue by atmadeep** [osmr/imgclsmob#72]
Might be a really naive question. Relatively new to keras and tensorflow.
The example cited in the gist returns a ops.EagerTensor instance and I was wondering how can I convert it into a tf.keras model instance and use it? (in order to freeze and remove layers)
![tf2cv](https://user-images.githubusercontent.com/22106111/88050858-43f58f00-cb75-11ea-8c75-6808d02131ea.png)

**Comment by atmadeep** [comment]
The `summary` method returns just the number of parameters as opposed to individual layers.

**Comment by osmr** [comment]
This question is more appropriate to ask at https://github.com/keras-team/keras or https://github.com/tensorflow/tensorflow.
