### ISSUE TITLE
Given pytorch pretrained model example failing as source url's missing 

### ISSUE THREAD

**Issue by SamSamhuns** [osmr/imgclsmob#77]
Excellent work btw. When I run the provided example in the `pytorchcv` dir, the pre-trained model weights are missing

```python
from pytorchcv.model_provider import get_model as ptcv_get_model
import torch
from torch.autograd import Variable

net = ptcv_get_model("resnet18", pretrained=True)
x = Variable(torch.randn(1, 3, 224, 224))
y = net(x)
```

I get the following error
```
download failed, retrying, 1 attempt left
Downloading /Users/username/.torch/models/resnet18-0896-77a56f15.pth.zip from https://github.com/osmr/imgclsmob/releases/download/v0.0.478
/resnet18-0896-77a56f15.pth.zip...
```

This URL is missing `https://github.com/osmr/imgclsmob/releases/download/`. @osmr, where are you hosting the pre-trained model weights? 

My System:
-   Mac OS Mojave 10.14.6
-   Python 3.7.9

**Comment by osmr** [comment]
Are you on the last commit?
