### ISSUE TITLE
"Unsupported model"

### ISSUE THREAD

**Issue by jon-huff** [osmr/imgclsmob#79]
Thanks for this project - great stuff!  Incidentally, I am trying to load ResNeSt101 in pytorch, but it's throwing a value error.  I've successfully loaded resnet, inception, etc.  Any thoughts?

ptcv_get_model("resnest101", pretrained=False)

**Comment by osmr** [comment]
Try the following:
```
net = ptcv_get_model("resnesta101", pretrained=False)
```
