### ISSUE TITLE
Random initialization of untrained models

### ISSUE THREAD

**Issue by jessicaloke** [osmr/imgclsmob#80]
Is it possible to set random seeds for the untrained models? How would I go about doing so?

**Comment by osmr** [comment]
Since the initialization of the network weights is a very sensitive thing for quality learning, initialization for all frameworks, except PyTorch, is your area of responsibility. Accordingly, depending on the framework, this is done in different ways.

**Comment by jessicaloke** [comment]
I'm doing this in PyTorch - how would I do so then?

**Comment by osmr** [comment]
Then weights are already randomly initialized. If you are interested in learning reproducibility, then pay attention to the function `torch.manual_seed()`.

**Comment by jessicaloke** [comment]
I see; I had use this function but i had thought that there could be a different way of initializing models. 
Thank you for the quick response! (:
