### ISSUE TITLE
PyTorch 1.6 torch.jit.trace doesn`t work properly. Error with division.

### ISSUE THREAD

**Issue by romanvey** [osmr/imgclsmob#81]
/home/roman/miniconda3/envs/ds/lib/python3.6/site-packages/pytorchcv/models/efficientnet.py` in forward(self, x)
    231     def forward(self, x):
    232         if self.tf_mode:
--> 233             x = F.pad(x, pad=calc_tf_padding(x, kernel_size=3, stride=2))
    234         x = self.conv(x)
    235         return x

/home/roman/miniconda3/envs/ds/lib/python3.6/site-packages/pytorchcv/models/efficientnet.py in calc_tf_padding(x, kernel_size, stride, dilation)
     45     """
     46     height, width = x.size()[2:]
---> 47     oh = math.ceil(height / stride)
     48     ow = math.ceil(width / stride)
     49     pad_h = max((oh - 1) * stride + (kernel_size - 1) * dilation + 1 - height, 0)

RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**Comment by osmr** [comment]
Try to run your code using the last commit of this repo (without using `pytorchcv` package).

**Comment by romanvey** [comment]
@osmr Yes, it works!
