### ISSUE TITLE
How can i load simplepose net?

### ISSUE THREAD

**Issue by who1129** [osmr/imgclsmob#82]
```
from tf2cv.model_provider import get_model as tf2cv_get_model
import tensorflow as tf


net = tf2cv_get_model("simplepose_resneta152b_coco", pretrained=True, data_format="channels_last")
x = tf.random.normal((1, 224, 224, 3))
y_net = net(x)
```

**I got this error. Do I need to change something??**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-933683f52df4> in <module>
----> 1 net = tf2cv_get_model("simplepose_resneta152b_coco", pretrained=True, data_format="channels_last")
      2 x = tf.random.normal((1, 224, 224, 3))
      3 y_net = net(x)

~/anaconda3/lib/python3.8/site-packages/tf2cv/model_provider.py in get_model(name, **kwargs)
    922     if name not in _models:
    923         raise ValueError("Unsupported model: {}".format(name))
--> 924     net = _models[name](**kwargs)
    925     return net

~/anaconda3/lib/python3.8/site-packages/tf2cv/models/simplepose_coco.py in simplepose_resneta152b_coco(pretrained_backbone, keypoints, data_format, **kwargs)
    309     backbone = resneta152b(pretrained=pretrained_backbone, data_format=data_format).features
    310     backbone._layers.pop()
--> 311     return get_simplepose(backbone=backbone, backbone_out_channels=2048, keypoints=keypoints,
    312                           model_name="simplepose_resneta152b_coco", data_format=data_format, **kwargs)
    313 

~/anaconda3/lib/python3.8/site-packages/tf2cv/models/simplepose_coco.py in get_simplepose(backbone, backbone_out_channels, keypoints, model_name, data_format, pretrained, root, **kwargs)
    136         input_shape = (1,) + (in_channels,) + net.in_size if net.data_format == "channels_first" else\
    137             (1,) + net.in_size + (in_channels,)
--> 138         net.build(input_shape=input_shape)
    139         net.load_weights(
    140             filepath=get_model_file(

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in build(self, input_shape)
    432                            'method accepts an `inputs` argument.')
    433         try:
--> 434           self.call(x, **kwargs)
    435         except (errors.InvalidArgumentError, TypeError):
    436           raise ValueError('You cannot build your model by calling `build` '

~/anaconda3/lib/python3.8/site-packages/tf2cv/models/simplepose_coco.py in call(self, x, training)
     83     def call(self, x, training=None):
     84         x = self.backbone(x, training=training)
---> 85         heatmap = self.decoder(x, training=training)
     86         if self.return_heatmap or not tf.executing_eagerly():
     87             return heatmap

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    939                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    940                 else:
--> 941                   outputs = call_fn(cast_inputs, *args, **kwargs)
    942 
    943             except errors.OperatorNotAllowedInGraphError as e:

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    260       except Exception as e:  # pylint:disable=broad-except
    261         if hasattr(e, 'ag_error_metadata'):
--> 262           raise e.ag_error_metadata.to_exception(e)
    263         else:
    264           raise

ValueError: in user code:

    /root/anaconda3/lib/python3.8/site-packages/tf2cv/models/common.py:2865 call  *
        x = block(x, training=training)
    /root/anaconda3/lib/python3.8/site-packages/tf2cv/models/common.py:2236 call  *
        x = self.conv(x)
    /root/anaconda3/lib/python3.8/site-packages/tf2cv/models/common.py:2156 call  *
        x = self.conv(x)
    /root/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:905 __call__  **
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    /root/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:176 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer conv is incompatible with the layer: expected ndim=4, found ndim=2. Full shape received: [1, 2048]

**Comment by osmr** [comment]
Upgrade `tf2cv` package and try again. Note that an input image should be `(1, 256, 192, 3)`.
