### ISSUE TITLE
Do you have plan of implementing

### ISSUE THREAD

**Issue by ghost** [osmr/imgclsmob#84]
Hi Oleg Sémery, great to see ResNeXt model. I'm so curious to know if you have plan of implementing Multi-Attention-Network over the ResNeXt ? https://arxiv.org/ftp/arxiv/papers/2009/2009.02130.pdf

**Comment by osmr** [comment]
Hi. The architecture does not seem difficult to implement. But I can hardly do it anytime soon :(
