### ISSUE TITLE
(tf)Resnesta  model  problems

### ISSUE THREAD

**Issue by Mrmdzz** [osmr/imgclsmob#86]
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (None, 128, 128, 2, 64). Consider casting elements to a supported type.
There is no problem with the other models I use.

**Comment by osmr** [comment]
Could you show me a minimal script to reproduce the error?

**Comment by Mrmdzz** [comment]
WARNING:tensorflow:Skipping loading of weights for layer output1 due to mismatch in shape ((2048, 5) vs (2048, 1000)).
WARNING:tensorflow:Skipping loading of weights for layer output1 due to mismatch in shape ((5,) vs (1000,)).
INFO:tensorflow:Error reported to Coordinator: in user code:
TypeError: in user code:

    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    C:\ProgramData\Anaconda3\lib\site-packages\tf2cv\models\resnesta.py:314 call  *
        x = self.features(x, training=training)
    C:\ProgramData\Anaconda3\lib\site-packages\tf2cv\models\common.py:2925 call  *
        x = block(x, training=training)
    C:\ProgramData\Anaconda3\lib\site-packages\tf2cv\models\common.py:2925 call  *
        x = block(x, training=training)
    C:\ProgramData\Anaconda3\lib\site-packages\tf2cv\models\resnesta.py:234 call  *
        x = self.body(x, training=training)
    C:\ProgramData\Anaconda3\lib\site-packages\tf2cv\models\resnesta.py:131 call  *
        x = self.conv2(x, training=training)
    C:\ProgramData\Anaconda3\lib\site-packages\tf2cv\models\common.py:2739 call  *
        x = self.att(x, training=training)
    C:\ProgramData\Anaconda3\lib\site-packages\tf2cv\models\common.py:2624 call  *
        x = tf.reshape(x, shape=(batch, height, width, self.radix, channels // self.radix))
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py:193 reshape  **
        result = gen_array_ops.reshape(tensor, shape, name)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:8087 reshape
        "Reshape", tensor=tensor, shape=shape, name=name)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:473 _apply_op_helper
        raise err
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:470 _apply_op_helper
        preferred_dtype=default_dtype)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py:1341 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py:321 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py:262 constant
        allow_broadcast=True)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py:300 _constant_impl
        allow_broadcast=allow_broadcast))
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py:547 make_tensor_proto
        "supported type." % (type(values), values))

    TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (None, 128, 128, 2, 64). Consider casting elements to a supported type.

**Comment by Mrmdzz** [comment]
minimal script:
model = tf2cv_get_model("resnesta50", pretrained=True, data_format="channels_last")
optimizer = tfa.optimizers.Lookahead(tfa.optimizers.RectifiedAdam(learning_rate=LR))
model.compile(...)
model.fit(...)

**Comment by osmr** [comment]
Do you use a `tf2cv` pip package? What version is it?

**Comment by Mrmdzz** [comment]
Is the latest version
Default used in the last 2-3 days   pip install tf2cv

**Comment by osmr** [comment]
Sorry. I can't reproduce your case using this description. It could be because of the different versions of TF/Keras or because I doesn't train the net with the `fit` function. I could suggest the following course of action: Please make a private repository containing minimal **working** code that reproduces the bug. In the readme, describe where to download the dataset. Add me to the repository. I'll debug the code and localize the error.

**Comment by Mrmdzz** [comment]
I'll try another version TF/Keras.Which version of TF / keras is suitable for this model library?

**Comment by osmr** [comment]
Theoretically any. Now I have TF 2.4.0 and Keras 2.3.1.

**Comment by nixingyang** [comment]
Hi,
I encountered a similar issue using TensorFlow 2.4.1.
Here is a minimal snippet to replicate it:
```python
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tf2cv.model_provider import get_model

raw_model = get_model(name="resnestabc14", pretrained=True)

# First case
input_tensor = Input(shape=(224, 224, 3), batch_size=64)
output_tensor = raw_model(input_tensor)
model = Model(inputs=input_tensor, outputs=output_tensor)

# Second case
input_tensor = Input(shape=(224, 224, 3))
output_tensor = raw_model(input_tensor)
model = Model(inputs=input_tensor, outputs=output_tensor)
```
The first case runs properly, while the second case crashes.
All the best.

**Comment by osmr** [comment]
Please check the effect of the last commit in the repository.

**Comment by Mrmdzz** [comment]
thanks

**Comment by nixingyang** [comment]
Thanks for the quick patch. The updated code works as expected.
