### ISSUE TITLE
PyTorch-SqueezeNext

### ISSUE THREAD

**Issue by NidhiSalian** [osmr/imgclsmob#9]
First off, thank you for compiling all these feature extractors implemented in different frameworks into a single repo. It's super useful while testing the performance of a new detection model.
I came here looking for a PyTorch implementation of SqueezeNext - following the link on [here](https://github.com/amirgholami/SqueezeNext).
I can't find anything on your lists though, not a single implementation of SqueezeNext. I found two repos being maintained independently([Tf](https://github.com/Timen/squeezenext-tensorflow) and [PyTorch](https://github.com/luuuyi/SqueezeNext.PyTorch)) and an old issue on your page.
I was wondering why you took it down, is there any particular reason why you've chosen not to include SqueezeNext?

**Comment by osmr** [comment]
Hi. The PyTorch script for SqueezeNext is here:
https://github.com/osmr/imgclsmob/blob/master/pytorch/pytorchcv/models/squeezenext.py

**Comment by NidhiSalian** [comment]
Didn't see that. Thank you!
