### ISSUE TITLE
Multiple outputs using PSPNet pre-trained model on Cityscapes

### ISSUE THREAD

**Issue by Swaraj-72** [osmr/imgclsmob#92]
Hello, 
When the PSPNet pre-trained model is used, the output is a tuple of 2 tensors. Can someone clarify what they are and how to achieve 1 output among them such that computation time can be saved?

net = get_model('pspnet_resnetd101b_cityscapes',pretrained_backbone=True,pretrained = True)
yp = net(X) 
yp.size()

This throws an error:
AttributeError                            Traceback (most recent call last)
<ipython-input-8-5ed6972650b2> in <module>
      1 yp = net(X) # model outputs 2 different learning rates
----> 2 yp.size()

AttributeError: 'tuple' object has no attribute 'size'

**Comment by osmr** [comment]
Check the following:
```
from pytorchcv.model_provider import get_model as ptcv_get_model
import torch
net = ptcv_get_model("pspnet_resnetd101b_cityscapes", pretrained=True, aux=False)
net.eval()
x = torch.randn(1, 3, 480, 480)
y = net(x)
```

**Comment by Swaraj-72** [comment]
Thanks for the response. It really helped me. One another thing I would like to know is about other input sizes which can be used.

I would like to use multi-scale processing which needs (3,240,240) and (3,120,120) as inputs to the network. Is it possible to achieve that using the model? Thank you.

**Comment by osmr** [comment]
Technically, yes:
```
net = ptcv_get_model("pspnet_resnetd101b_cityscapes", pretrained=True, in_size=(120, 120), aux=False)
```

**Comment by Swaraj-72** [comment]
Thank you for the reply. It helped me a lot with my project.

**Comment by Swaraj-72** [comment]
The pretrained_backbone option provided hasn't seemed to be having a major effect on the predictions. I have tried both booleans and the results did not differ much. 
Could you please let me know whether it is to be used any differently to improve the predictions. Thank you.

**Comment by osmr** [comment]
The `pretrained_backbone` option is for training.

**Comment by Swaraj-72** [comment]
Thank you for the quick response.
